name: flutter_template
description: A new Flutter project.

version: 2.0.0+2

environment:
  sdk: ">=2.2.0 <3.0.0"

# 依赖库
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^2.0.0
  eva_icons_flutter: ^2.0.1
  cookie_jar: ^1.0.1
  cupertino_icons: ^1.0.3
  date_format: ^2.0.2
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  extended_image: ^2.0.0
  event_bus: ^2.0.0
  flutter_easyrefresh: ^2.2.1
  flutter_spinkit: ^5.0.0
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.11
  flutter_xupdate: ^2.0.0
  get: ^4.1.4
  oktoast: ^3.0.0
  path_provider: ^1.6.1
  package_info: ^2.0.2
  permission_handler: ^7.2.0
  provider: ^5.0.0
  shared_preferences: ^0.5.7+3
  share: ^2.0.4
  url_launcher: ^6.0.6

  bloc: ^7.0.0
  rxdart: ^0.26.0
  flutter_rating_bar: ^3.2.0+1
  page_indicator: ^0.2.1
  font_awesome_flutter: ^8.12.0
  sliver_fab: ^1.0.0
  youtube_player_flutter: ^6.1.1
  auto_route: ^2.2.0

  cloudbase_core: ^0.0.6
  cloudbase_auth: ^0.0.7
  cloudbase_function: ^0.0.2
  cloudbase_storage: ^0.0.3
  cloudbase_database: ^0.0.9

  like_button: ^0.1.9

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/blackLogo.png"

# 字体、图标、图片等资源加载
flutter:
  uses-material-design: true
  assets:
  - assets/image/


  fonts:
    - family: xuifont
      fonts:
        - asset: assets/fonts/iconfont.ttf